/**
 *
 * $Id$
 */
package sensingflow.model.validation;

import org.eclipse.emf.common.util.EList;
import sensingflow.model.SensingflowInPort;
import sensingflow.model.SensingflowTaskType;


/**
 * A sample validator interface for {@link sensingflow.model.SensingflowTask}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SensingflowTaskValidator {
	boolean validate();

	boolean validateInPorts(EList<SensingflowInPort> value);

	boolean validateOperatorName(SensingflowTaskType value);

	boolean validateTaskType(SensingflowTaskType value);

}
