/**
 *
 * $Id$
 */
package sensingflow.model.validation;

import sensingflow.model.SensingflowSensorType;


/**
 * A sample validator interface for {@link sensingflow.model.SensingflowSensor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SensingflowSensorValidator {
	boolean validate();

	boolean validateFrameSize(int value);

	boolean validateSubFrameSize(int value);

	boolean validateOperatorName(SensingflowSensorType value);

	boolean validateSensorType(SensingflowSensorType value);

	boolean validateSubFrameSlidingSize(int value);

	boolean validateSubInterval(int value);

}
