/**
 *
 * $Id$
 */
package sensingflow.model.validation;

import sensingflow.model.SensingflowThing;


/**
 * A sample validator interface for {@link sensingflow.model.SensingflowOutPort}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SensingflowOutPortValidator {
	boolean validate();

	boolean validateOutputSize(int value);

	boolean validateThing(SensingflowThing value);

	boolean validateFrameSize(int value);

	boolean validateSubFrameSize(int value);

	boolean validateSubFrameSlidingSize(int value);

	boolean validateFrameInterval(int value);

}
