/**
 *
 * $Id$
 */
package sensingflow.model.validation;

import org.eclipse.emf.common.util.EList;

import sensingflow.model.SensingflowNode;

/**
 * A sample validator interface for {@link sensingflow.model.SensingflowContainer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SensingflowContainerValidator {
	boolean validate();

	boolean validateNodes(EList<SensingflowNode> value);

	boolean validateId(int value);

	boolean validateId(EList<Integer> value);
}
