/**
 *
 * $Id$
 */
package sensingflow.model.validation;

import org.eclipse.emf.common.util.EList;
import sensingflow.model.SensingflowOutPort;


/**
 * A sample validator interface for {@link sensingflow.model.SensingflowThing}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SensingflowThingValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateLogicParameter(String value);

	boolean validateDeviceId(String value);

	boolean validateInstantParameter(String value);

	boolean validateOutPorts(EList<SensingflowOutPort> value);

	boolean validateLogicParameter2(String value);
}
