/**
 *
 * $Id$
 */
package sensingflow.model.validation;

import org.eclipse.draw2d.geometry.Rectangle;

import org.eclipse.emf.common.util.EList;

import sensingflow.model.SensingflowContainer;
import sensingflow.model.SensingflowLink;

/**
 * A sample validator interface for {@link sensingflow.model.SensingflowNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SensingflowNodeValidator {
	boolean validate();

	boolean validateIncomingLinks(EList<SensingflowLink> value);
	boolean validateOutgoingLinks(EList<SensingflowLink> value);
	boolean validateContainer(SensingflowContainer value);
	boolean validateConstraints(Rectangle value);

	boolean validateTest(boolean value);
}
